import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const router = useRouter();
  const [user, setUser] = useState({
    userEmail: "",
  });

  const callAPI = async () => {
    try {
      console.log(user);
      const userProfile = await fetch("https://chhota-url.herokuapp.com/chhotaUrl/user", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
        body: JSON.stringify(user),
      }).then(data => data.json());

      router.replace({
        pathname: "/chhotaUrl",
        query: { userEmail: userProfile.userEmail, userId : userProfile.userId },
      });

    } catch (err) {
      console.log(err);
    }
  };

  const handleChange = () => (e) => {
    const value = e.target.value;
    const name = e.target.name;
    setUser((prevState) => ({
      ...prevState,
      [name]: value,
    }));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">ChhotaURL</a>
        </h1>
        <p className={styles.description}>Enter Your Email To Start</p>
        <div>
          <input
            className={styles.input}
            required
            type="email"
            id="userEmail"
            name="userEmail"
            placeholder="Enter Your Email"
            value={user.userEmail}
            onChange={handleChange()}
          />
          <button className={styles.submitButton} onClick={callAPI}>
            Start
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
